import Image from "next/image";
import Link from "next/link";
import { assetPath, mediaPath, isDemo } from "@/lib/deployment";
import { ArrowDown, ArrowDownRight, ArrowUpRight, Crosshair, Fingerprint, Heart, Plus, Star } from "lucide-react";
import { Navigation } from "@/components/navigation";
import { Artwork } from "@/components/artwork";
import { Portfolio } from "@/components/portfolio";
import { BookingForm } from "@/components/booking-form";
import { faqs, masters, prices, reviews, site } from "@/lib/content";
import { getGallery } from "@/lib/gallery";

export const dynamic = "force-dynamic";
function SectionLabel({ number, children }: { number: string; children: React.ReactNode }) { return <div className="section-label mono"><span>[ {number} ]</span>{children}</div>; }

export default async function Home() {
  const gallery = await getGallery();
  return <>
    <a className="skip-link" href="#main">К содержимому</a>
    <Navigation/>
    <main id="main">
      <section className="hero" aria-labelledby="hero-heading">
        <div className="hero-photo"><Image src={assetPath("/images/hero.webp")} alt="Мастер в перчатках наносит татуировку" fill priority sizes="100vw"/><div className="hero-shade"/></div>
        <div className="hero-content"><p className="eyebrow mono"><span className="status-dot"/>ТАТУ-СТУДИЯ ДЛЯ ТЕХ, КТО ЧУВСТВУЕТ</p><h1 id="hero-heading">ТВОЯ КОЖА.<br/>ТВОИ <span>ПРАВИЛА.</span></h1><p className="hero-description">Истории, которые остаются с тобой.<br/>Создаём татуировки с характером — твоим.</p><a href="#booking" className="button hero-button">Обсудить свою идею <ArrowUpRight size={22}/></a><a className="hero-secondary" href="#portfolio">Почувствовать наш стиль <ArrowDown size={15}/></a></div>
        <div className="hero-bottom mono"><span>МОСКВА / {site.address.split("Москва, ")[1].toUpperCase()}</span><span className="hero-bottom-center">ТВОЁ ТЕЛО — ТВОЁ ИСКУССТВО</span><a href="#about" aria-label="Дальше о студии"><ArrowDown size={20}/></a></div>
      </section>

      <section className="section about-section container" id="about"><SectionLabel number="01">ЭТО ВАЙБ</SectionLabel><div className="about-layout"><h2>НЕ ПРОСТО ТАТУ.<br/>ЧАСТЬ <span className="muted">ТЕБЯ.</span><span className="orange small-asterisk" aria-hidden="true">✳</span></h2><div className="about-copy"><p>Мы верим, что лучшая татуировка — та, в которой ты узнаёшь себя. Без чужих ожиданий. Без случайных линий.</p><p className="muted">ВАЙБ — пространство, где можно быть собой. Приходи с готовой идеей или с одним только чувством. Вместе найдём для него форму.</p><a className="text-link" href="#masters">Знакомься со своими людьми <ArrowDownRight size={20}/></a></div></div><div className="values-grid">{[[Fingerprint, "Твой характер", "Индивидуальный эскиз под твою идею и анатомию."], [Crosshair, "Внимание к деталям", "От первой линии до рекомендаций по уходу."], [Heart, "Спокойно и по-своему", "Без спешки, давления и неудобных вопросов."]].map(([Icon, title, description], i) => { const ValueIcon = Icon as typeof Heart; return <div className="value" key={i}><ValueIcon size={26} strokeWidth={1.3}/><div><h3>{title as string}</h3><p>{description as string}</p></div></div>; })}</div></section>

      <section className="section masters-section container" id="masters"><SectionLabel number="02">ТВОИ ЛЮДИ</SectionLabel><div className="section-heading"><h2>РАЗНЫЕ СТИЛИ.<br/>ОДИН <span className="orange">ВАЙБ.</span></h2><p>Три мастера. Три взгляда на искусство.<br/>Найди того, кто чувствует так же.</p></div><div className="masters-grid">{masters.map((master, i) => { const photo = gallery.find(item => item.kind === "master" && item.master === master.id); return <article className="master-card" key={master.id}><div className={`master-visual master-${i}`}><span className="master-no mono">/ 0{i+1}</span>{photo ? <Image src={mediaPath(photo.id)} alt={`Тату-мастер ${master.name}`} fill sizes="(max-width: 650px) 100vw, 33vw"/> : <><Artwork kind={master.symbol}/><span className="master-placeholder mono">ARTIST / {master.id.toUpperCase()}</span></>}<a href="#booking" className="round-arrow" aria-label={`Записаться к мастеру ${master.name}`}><ArrowUpRight size={24}/></a></div><div className="master-title"><h3>{master.name}</h3><span className="mono">TATTOO ARTIST</span></div><p className="master-role mono">{master.role}</p><p className="master-description">{master.text}</p></article>; })}</div></section>

      <section className="section portfolio-section container" id="portfolio"><SectionLabel number="03">ЧЕРНИЛА ГОВОРЯТ</SectionLabel><div className="section-heading"><h2>БОЛЬШЕ, ЧЕМ<br/><span className="muted">РИСУНОК.</span></h2><p>От тонкой линии до смелого сюжета.<br/>Твой стиль начинается с отклика.</p></div><Portfolio works={gallery.filter(item => item.kind === "work")}/><div className="portfolio-bottom"><p>Есть своя идея? Нам уже интересно.</p><a className="text-link" href="#booking">Давай обсудим <ArrowUpRight size={19}/></a></div></section>

      <section className="prices-wrap" id="prices"><div className="section container"><SectionLabel number="04">ЧЕСТНО О СТОИМОСТИ</SectionLabel><div className="section-heading"><h2>ИСКУССТВО.<br/>БЕЗ СЮРПРИЗОВ.</h2><p>Стоимость зависит от стиля, размера<br/>и сложности. Всё обсудим заранее.</p></div><div className="price-table-wrap"><table className="price-table"><caption className="sr-only">Стоимость татуировок по направлениям</caption><thead><tr><th scope="col">НАПРАВЛЕНИЕ</th><th scope="col">СТОИМОСТЬ</th><th scope="col"><span className="sr-only">Запись</span></th></tr></thead><tbody>{prices.map((p, i) => <tr key={i}><td><span className="price-number mono">0{i+1}</span><div><h3>{p.title}</h3><p>{p.description}</p></div></td><td><span className="price-amount">{p.price}</span><span className="price-currency"> ₽</span></td><td><a href="#booking" aria-label={`Обсудить ${p.title}`}><ArrowUpRight size={26}/></a></td></tr>)}</tbody></table></div><div className="price-note"><span className="mono">НИКАКИХ СЛУЧАЙНЫХ РЕШЕНИЙ</span><p>Точная стоимость и объём работы согласуются с мастером до сеанса.</p></div></div></section>

      <section className="section faq-section container" id="faq"><div><SectionLabel number="05">БЕЗ ЛИШНИХ ПЕРЕЖИВАНИЙ</SectionLabel><h2>ЕСТЬ ВОПРОСЫ?<br/><span className="muted">ЭТО НОРМАЛЬНО.</span></h2><p className="faq-intro">Первое тату или десятое —<br/>мы всегда готовы всё объяснить.</p><ArrowDownRight className="faq-arrow" size={74} strokeWidth={1}/></div><div className="faq-list">{faqs.map((faq, i) => <details key={faq.question} name="faq"><summary><span className="mono faq-number">0{i+1}</span><h3>{faq.question}</h3><Plus size={21}/></summary><div className="faq-answer"><p>{faq.answer}</p>{faq.source && <a href={faq.source} target="_blank" rel="noopener noreferrer">Памятка Европейской академии дерматологии ↗</a>}</div></details>)}</div></section>

      <section className="section reviews-section container" id="reviews"><SectionLabel number="06">ПОСЛЕ СЕАНСА</SectionLabel><div className="section-heading"><h2>ОСТАЁТСЯ ТАТУ.<br/>И <span className="orange">ВПЕЧАТЛЕНИЕ.</span></h2><p>Самое ценное — когда<br/>хочется вернуться.</p></div><div className="reviews-grid">{reviews.map(r => <article className="review" key={r.name}><div className="stars" aria-label="5 из 5">{Array.from({length:5},(_,i)=><Star key={i} size={14} fill="currentColor"/>)}</div><blockquote>«{r.text}»</blockquote><div className="review-person"><span className="review-avatar">{r.name[0]}</span><div><h3>{r.name}</h3><p>{r.style}</p></div></div></article>)}</div><p className="demo-note review-note">Примеры отзывов для макета. Имена и истории вымышлены.</p></section>

      <section className="booking-section" id="booking"><div className="container booking-layout"><div className="booking-copy"><SectionLabel number="07">НАЧНЁМ С РАЗГОВОРА</SectionLabel><h2>ЕСТЬ ИДЕЯ?<br/>ЕСТЬ <span className="orange">ВАЙБ.</span></h2><p>Не обязательно знать все ответы.<br/>Расскажи, что у тебя на уме —<br/>остальное придумаем вместе.</p><div className="booking-art" aria-hidden="true"><span>let’s make</span><span>something</span><span className="outline-text">personal.</span><ArrowUpRight size={66} strokeWidth={1}/></div></div><BookingForm/></div></section>

      <section className="section contacts-section container" id="contacts"><SectionLabel number="08">МЕСТО ВСТРЕЧИ</SectionLabel><div className="contact-layout"><h2>УВИДИМСЯ<br/><span className="muted">В СТУДИИ.</span></h2><div className="contact-details"><span className="mono">ТАТУ-СТУДИЯ ВАЙБ / МОСКВА</span><address>ул. Примерная, 199</address><p>Встречаемся по предварительной записи.</p><a href="https://yandex.ru/maps/?text=Москва%20ул.%20Примерная%20199" target="_blank" rel="noopener noreferrer" className="text-link">Открыть в Яндекс Картах <ArrowUpRight size={20}/></a></div><a href="#booking" className="contact-circle" aria-label="Записаться в студию"><ArrowUpRight size={66} strokeWidth={1}/></a></div></section>
    </main>
    <footer className="footer"><div className="footer-top container"><span className="mono">ТВОЯ КОЖА. ТВОИ ПРАВИЛА.</span><a href="#" className="mono">НАВЕРХ <ArrowUpRight size={17}/></a></div><div className="footer-wordmark" aria-hidden="true">вайб<span>✳</span></div><div className="footer-bottom container"><span>© {new Date().getFullYear()} ВАЙБ{isDemo ? " · ДЕМО-ПРОЕКТ" : ""}</span><Link href="/privacy">{isDemo ? "О демо и данных" : "Политика конфиденциальности"}</Link><span>СДЕЛАНО С ХАРАКТЕРОМ</span></div></footer>
  </>;
}
